IF
	OnCreation()
THEN
	RESPONSE #100
		ApplySpellRES("AC#DTPL",Myself)  // Shadow color
		SetName(@1012)  // <Player2>'s Schatten
		DestroyItem("AC#DTPLS")  // Unsichtbarkeitsring
		CreateVisualEffectObject("AC#DTFLS",Myself)
END

IF
	Die()
THEN
	RESPONSE #100
		CreateVisualEffectObject("AC#DTFLS",Myself)
		DestroySelf()
END

IF
	See(Player2)
THEN
	RESPONSE #100
		Attack(Player2)
END

IF
	!See(Player2)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Attack(NearestEnemyOf(Myself))
END

