IF
	OnCreation()
THEN
	RESPONSE #100
		ApplySpellRES("AC#DTPL",Myself)  // Shadow color
		SetName(@1016)  // <Player6>'s Schatten
		DestroyItem("AC#DTPLS")  // Unsichtbarkeitsring
		CreateVisualEffectObject("AC#DTFLS",Myself)
END

IF
	Die()
THEN
	RESPONSE #100
		CreateVisualEffectObject("AC#DTFLS",Myself)
		DestroySelf()
END

IF
	See(Player6)
THEN
	RESPONSE #100
		Attack(Player6)
END

IF
	!See(Player6)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Attack(NearestEnemyOf(Myself))
END

