IF
	OnCreation()
THEN
	RESPONSE #100
		ApplySpellRES("AC#DTPL",Myself)  // Shadow color
		SetName(@1011)  // <PLAYER1>'s Schatten
		DestroyItem("AC#DTPLS")  // Unsichtbarkeitsring
		CreateVisualEffectObject("AC#DTFLS",Myself)
END

IF
	Die()
THEN
	RESPONSE #100
		CreateVisualEffectObject("AC#DTFLS",Myself)
		DestroySelf()
END

IF
	See(Player1)
THEN
	RESPONSE #100
		Attack(Player1)
END

IF
	!See(Player1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Attack(NearestEnemyOf(Myself))
END

