// Runestone Info Trigger
IF
	Clicked([ANYONE])
	Global("ReadRunestone","ACDT21",0)
THEN
	RESPONSE #100
		DisplayString(Myself,@1030)
		SetGlobal("ReadRunestone","ACDT21",1)   
END

IF
	Clicked([ANYONE])
	Global("ReadRunestone","ACDT21",1) 
	Global("NPCRunestoneReaction","ACDT21",0)
THEN
	RESPONSE #100
		DisplayString(Myself,@1031) 
		SetGlobal("NPCRunestoneReaction","ACDT21",1)  
END

IF
	Clicked([ANYONE])
THEN
	RESPONSE #100
		DisplayString(Myself,@1031)  // the runestone inscription
END

